# Part 1: Creating ndarrays

1. Convert the below given list of strings to a int32 NumPy array

In [3]:
import numpy as np

In [11]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']

In [22]:
ar = np.array(slist)
ar = ar.astype(float)
ar = ar.astype(int)
ar

array([   2,    1,    0,    2, 1024])

2. Create an empty 5x5 NumPy matrix

In [30]:
arr = np.empty((5,5))
arr

array([[1.86918699e-306, 1.69121096e-306, 1.95820216e-306,
        1.37961641e-306, 2.04721734e-306],
       [6.23053614e-307, 1.20161797e-306, 6.23058707e-307,
        9.34611148e-307, 1.29061889e-306],
       [6.23060065e-307, 1.06810268e-306, 8.06632139e-308,
        1.60218491e-306, 1.02360867e-306],
       [1.95821439e-306, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.60219035e-306,
        1.33511969e-306, 2.56765117e-312]])

# Part 2: Operations between Arrays and Scalars

3. Create a 1x25 Numpy array whose elements consist of geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [33]:
sample_output = [1,3,9,27,81]

In [34]:
arr = np.arange(0,26)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [50]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
tarry = arr%2
tarry

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [52]:
arr[tarry.astype(bool)] = 0
arr

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [53]:
arr = np.arange(16).reshape((2, 2, 4))

In [54]:
arr.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [55]:
arr.transpose((1, 2, 0))

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])